#!/bin/bash
# Complete GMS Deployment Instructions
# Run each section step by step

echo "========================================="
echo "  GMS Complete Deployment Guide"
echo "========================================="
echo ""
echo "STEP 1: Upload update script to VPS"
echo "Run this from your LOCAL machine:"
echo ""
echo "cd /Users/papuman/Documents/My\ Projects/GMS/deployment"
echo "scp update-vps.sh root@168.231.71.94:/root/"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 2: SSH into VPS and run update"
echo "Run these commands:"
echo ""
echo "ssh root@168.231.71.94"
echo "bash /root/update-vps.sh"
echo "# Wait for completion (~5-10 minutes)"
echo "reboot"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 3: Wait 2 minutes, then edit .env"
echo "After VPS reboots, configure passwords:"
echo ""
echo "cd /Users/papuman/Documents/My\ Projects/GMS/deployment"
echo "nano .env"
echo ""
echo "Change these 4 values:"
echo "  - ACME_EMAIL"
echo "  - POSTGRES_PASSWORD_STAGE"
echo "  - POSTGRES_PASSWORD_PROD"
echo "  - TRAEFIK_AUTH"
echo ""
echo "Generate TRAEFIK_AUTH:"
echo "  htpasswd -nb admin YourPassword"
echo "  Copy output, replace \$ with \$\$"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 4: Deploy GMS"
echo "Run deployment script:"
echo ""
echo "./deploy.sh"
echo "# Takes ~5 minutes"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 5: Access your systems"
echo ""
echo "Staging: https://stage.blanchedalmond-raccoon-234970.hostingersite.com"
echo "Production: https://blanchedalmond-raccoon-234970.hostingersite.com"
echo ""
echo "========================================="
